### ISSUE TITLE
Index wrong for C

### ISSUE THREAD

**Issue by tsihyoung** [ECoulter/Kronecker#1]
In ``function KronProd(A,B) result(C)``
``m=n+size(B,1)``
``q=p+size(B,2)``
should be
``m=n+size(B,1)-1``
``q=p+size(B,2)-1``

**Comment by shawnstrausser** [comment]
Thank you @tsihyoung, I agree with your comment.

**Comment by ECoulter** [comment]
Huh, I didn't expect anyone to ever use this - thanks for letting me know @tsihyoung @shawnstrausser ! Not sure how that escaped testing... 
Fixed in the latest commits.
